"""add knowledge table

Revision ID: a7a038514b7c
Revises: f3069f28699a
Create Date: 2024-07-15 05:44:30.319565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7a038514b7c'
down_revision: Union[str, None] = 'f3069f28699a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('type', sa.Enum('DOCUMENT', 'SHEET', 'IMAGE',
                                              name='knowledgetype'), nullable=False),
                    sa.Column('avatar', sa.String(length=255), nullable=True),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_by', sa.Integer(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('knowledge_config',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_by', sa.Integer(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('knowledge_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['knowledge_id'], ['knowledge.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('knowledge_document_config',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('mode', sa.Enum('AUTO', 'CUSTOM',
                              name='splittype'), nullable=True),
                    sa.Column('chunk_size', sa.String(
                        length=255), nullable=True),
                    sa.Column('identifier', sa.String(
                        length=255), nullable=True),
                    sa.Column('text_preprocessing_rules',
                              sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['knowledge_config.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('chunk_size')
                    )
    op.create_table('knowledge_image_config',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('mode', sa.String(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['knowledge_config.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('knowledge_sheet_config',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('headers', sa.Text(), nullable=True),
                    sa.Column('structure', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['knowledge_config.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # op.alter_column('messages', 'message_type',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.Enum('MARKDOWN', 'TEXT', name='messagetype'),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'message_type',
                    existing_type=sa.Enum(
                        'MARKDOWN', 'TEXT', name='messagetype'),
                    type_=sa.VARCHAR(length=50),
                    existing_nullable=False)
    op.drop_table('knowledge_sheet_config')
    op.drop_table('knowledge_image_config')
    op.drop_table('knowledge_document_config')
    op.drop_table('knowledge_config')
    op.drop_table('knowledge')
    # ### end Alembic commands ###
