"""add plugin table

Revision ID: ac21c38c5e56
Revises: 5918599719a1
Create Date: 2024-07-02 09:56:29.437606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac21c38c5e56'
down_revision: Union[str, None] = '5918599719a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('plugin_type', sa.Integer(), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_by', sa.Integer(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('plugin_config',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('avatar', sa.String(length=255), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('plugin_id', sa.Integer(), nullable=True),
                    sa.Column('is_draft', sa.Boolean(), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_by', sa.Integer(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('plugin_api',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('plugin_config_id', sa.Integer(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('openapi_desc', sa.Text(), nullable=True),
                    sa.Column('disabled', sa.Boolean(), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_by', sa.Integer(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['plugin_config_id'], [
                                            'plugin_config.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('messages', 'message_type',
                    type_=sa.VARCHAR(length=50),
                    existing_type=sa.Enum(
                        'MARKDOWN', 'TEXT', name='messagetype'),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'message_type',
                    existing_type=sa.Enum(
                        'MARKDOWN', 'TEXT', name='messagetype'),
                    type_=sa.VARCHAR(length=50),
                    existing_nullable=False)
    op.drop_table('plugin_api')
    op.drop_table('plugin_config')
    op.drop_table('plugin')
    # ### end Alembic commands ###
