"""update plugin api table

Revision ID: df31d751e3d7
Revises: a7a038514b7c
Create Date: 2024-07-17 09:25:05.071105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df31d751e3d7'
down_revision: Union[str, None] = 'a7a038514b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin_api', sa.Column(
        'server_url', sa.String(length=255), nullable=True))
    op.add_column('plugin_api', sa.Column(
        'method', sa.String(length=255), nullable=True))
    op.add_column('plugin_api', sa.Column(
        'summary', sa.String(length=255), nullable=True))
    op.add_column('plugin_api', sa.Column(
        'parameters', sa.JSON(), nullable=True))
    op.add_column('plugin_api', sa.Column(
        'operation_id', sa.String(length=255), nullable=True))
    op.alter_column('plugin_api', 'openapi_desc',
                    existing_type=sa.TEXT(),
                    type_=sa.JSON(),
                    existing_nullable=True,
                    postgresql_using="openapi_desc::json")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugin_api', 'openapi_desc',
                    existing_type=sa.JSON(),
                    type_=sa.TEXT(),
                    existing_nullable=True,
                    postgresql_using="openapi_desc::text")
    op.drop_column('plugin_api', 'operation_id')
    op.drop_column('plugin_api', 'parameters')
    op.drop_column('plugin_api', 'summary')
    op.drop_column('plugin_api', 'method')
    op.drop_column('plugin_api', 'server_url')
    # ### end Alembic commands ###
