"""update plugin table

Revision ID: f3069f28699a
Revises: ac21c38c5e56
Create Date: 2024-07-11 04:20:39.013033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3069f28699a'
down_revision: Union[str, None] = 'ac21c38c5e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin', sa.Column(
        'name', sa.String(length=255), nullable=False))
    op.add_column('plugin', sa.Column(
        'avatar', sa.String(length=255), nullable=True))
    op.add_column('plugin', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('plugin_api', sa.Column(
        'name', sa.String(length=255), nullable=True))
    op.add_column('plugin_config', sa.Column(
        'plugin_openapi_desc', sa.Text(), nullable=True))
    op.drop_column('plugin_config', 'avatar')
    op.drop_column('plugin_config', 'description')
    op.drop_column('plugin_config', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin_config', sa.Column('name', sa.VARCHAR(
        length=255), autoincrement=False, nullable=False))
    op.add_column('plugin_config', sa.Column(
        'description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('plugin_config', sa.Column('avatar', sa.VARCHAR(
        length=255), autoincrement=False, nullable=True))
    op.drop_column('plugin_config', 'plugin_openapi_desc')
    op.drop_column('plugin_api', 'name')
    op.drop_column('plugin', 'description')
    op.drop_column('plugin', 'avatar')
    op.drop_column('plugin', 'name')
    op.alter_column('messages', 'message_type',
                    existing_type=sa.Enum(
                        'MARKDOWN', 'TEXT', name='messagetype'),
                    type_=sa.VARCHAR(length=50),
                    existing_nullable=False)
    # ### end Alembic commands ###
