"""update plugin config table

Revision ID: f54e1fc0bd90
Revises: df31d751e3d7
Create Date: 2024-07-21 14:41:06.251765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54e1fc0bd90'
down_revision: Union[str, None] = 'df31d751e3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin_config', sa.Column('apis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugin_config', 'apis')
    op.alter_column('messages', 'message_type',
               existing_type=sa.Enum('MARKDOWN', 'TEXT', name='messagetype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
